In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
from torchvision.transforms import Normalize
from collections import namedtuple
import torch.nn as nn

#importing Technical Analysis tools
from ta import trend
from ta import volatility
from ta import momentum

import utils
from utils import return_fun

In [2]:
reuters=pd.read_csv("data/reut_data.csv",sep='|')

sx5e_data=pd.read_csv("data\SX5E.csv")

In [3]:
sx5e_data = sx5e_data.sort_index(axis=0 ,ascending=False)
sx5e_data.reset_index(drop=True,inplace=True)
sx5e_data['Date']=pd.to_datetime(sx5e_data.Date)

sx5e_data.dropna(inplace=True)


adi=trend.ADXIndicator(close=sx5e_data[' Close'],high=sx5e_data[' High'],low=sx5e_data[' Low'])
m_acd=trend.MACD(close=sx5e_data[' Close'])

r_si=momentum.RSIIndicator(close=sx5e_data[' Close'])
stochastic_oscilator=momentum.StochasticOscillator(close=sx5e_data[' Close'],high=sx5e_data[' High'],low=sx5e_data[' Low'])
williamsr=momentum.WilliamsRIndicator(high=sx5e_data[' High'],low=sx5e_data[' Low'],close=sx5e_data[' Close'])

bollinger=volatility.BollingerBands(close=sx5e_data[' Close'])
atr=volatility.AverageTrueRange(high=sx5e_data[' High'],low=sx5e_data[' Low'],close=sx5e_data[' Close'])

exponential_moving_avarge9=trend.EMAIndicator(close=sx5e_data[' Close'],window=9)
exponential_moving_avarge18=trend.EMAIndicator(close=sx5e_data[' Close'],window=18)
exponential_moving_avarge30=trend.EMAIndicator(close=sx5e_data[' Close'],window=30)

sx5e_data['ADX']=adi.adx()
sx5e_data['MACD']=m_acd.macd()
sx5e_data['RSI']=r_si.rsi()
sx5e_data['Stoch Osc']=stochastic_oscilator.stoch()
sx5e_data['Williams R']=williamsr.williams_r()
sx5e_data['Bollinger High band']=bollinger.bollinger_hband()
sx5e_data['Bolinger Low Band']=bollinger.bollinger_lband()
sx5e_data['ATR']=atr.average_true_range()
sx5e_data['EMA9']=exponential_moving_avarge9.ema_indicator()
sx5e_data['EMA18']=exponential_moving_avarge18.ema_indicator()
sx5e_data['EMA30']=exponential_moving_avarge30.ema_indicator()
sx5e_data.dropna(inplace=True)
ret_fun=return_fun(sx5e_data,1,4)
sx_ret=sx5e_data.copy()
sx_ret['Ret']=ret_fun
sx_ret.drop(columns=['ADX','MACD','RSI','Stoch Osc','Williams R','Bollinger High band','Bolinger Low Band','ATR','EMA9','EMA18','EMA30',' Open',' High',' Low'],inplace=True)

c:\users\48694\appdata\local\programs\python\python39\lib\site-packages\ta\trend.py:768: RuntimeWarning: invalid value encountered in double_scalars
  dip[i] = 100 * (self._dip[i] / self._trs[i])
c:\users\48694\appdata\local\programs\python\python39\lib\site-packages\ta\trend.py:772: RuntimeWarning: invalid value encountered in double_scalars
  din[i] = 100 * (self._din[i] / self._trs[i])


In [4]:
reuters.drop(columns='column1',inplace=True)
reuters.drop_duplicates(subset ="Headline",
                     keep = 'first', inplace = True)
reuters.dropna(inplace=True)
reuters.reset_index(drop=True,inplace=True)

for i in range(len(reuters)):
    text=reuters['Headline'][i]
    text=text.replace("REFILE-UPDATE 2-","")
    text=text.replace("UPDATE 2-","")
    text=text.replace("UPDATE 1-","")
    text=text.replace("UPDATE ","")
    text=text.replace(",","")
    text=text.replace(".","")
    text=text.replace(";","")
    text=text.replace(":","")
    text=text.replace("-","")
    text=text.replace("European","")
    reuters['Headline'][i]=text

In [5]:
reuters['Date']=pd.to_datetime(reuters.Date)

In [6]:

lang=utils.Lang('t')

for i in range(len(reuters)):
    sentence=reuters['Headline'][i]
    lang.addSentence(sentence)

In [7]:
# sx5e_data.drop(columns='Date',inplace=True)
sx5e_data.drop(sx5e_data.tail(1).index,inplace=True)
# sx5e_tensor=torch.tensor(sx5e_data.values)

In [8]:
ret_fun.remove(None)
tensor_ret=torch.tensor(ret_fun,dtype=torch.float32)
mean_ret=torch.mean(tensor_ret)
std_ret=torch.std(tensor_ret)

In [9]:
sx5e_data.drop(columns='Date',inplace=True)
# sx5e_data.drop(sx5e_data.tail(1).index,inplace=True)
sx5e_tensor=torch.tensor(sx5e_data.values)

In [10]:
mean=torch.mean(sx5e_tensor,dim=0)
std=torch.std(sx5e_tensor,dim=0)
sx5e_norm=(sx5e_tensor-mean)/std
print(sx5e_norm)

tensor([[-0.9221, -0.9442, -1.0001,  ..., -0.9280, -0.8126, -0.7074],
        [-0.9531, -0.9766, -0.9926,  ..., -0.9452, -0.8345, -0.7281],
        [-0.9801, -0.9924, -0.9511,  ..., -0.9550, -0.8519, -0.7462],
        ...,
        [ 2.1637,  2.3829,  2.2003,  ...,  2.2373,  2.3354,  2.4011],
        [ 2.4110,  2.4069,  2.3607,  ...,  2.2597,  2.3400,  2.4022],
        [ 2.3454,  2.3174,  2.2942,  ...,  2.2670,  2.3384,  2.3997]],
       dtype=torch.float64)


In [11]:
sx_ret.dropna(inplace=True)

In [12]:
sx_ret.head()

Date    Close       Ret
29 2010-02-11  2680.25 -0.216025
30 2010-02-12  2674.46  0.350351
31 2010-02-15  2683.83  1.376391
32 2010-02-16  2720.77  1.524568
33 2010-02-17  2762.25  0.581048

In [13]:
date=sx_ret['Date'][3104]
headline=reuters[reuters['Date']==date].iloc[0]
print(headline['Headline'])
print(sx_ret['Ret'][3104])
print(date)

 shares fall again on Omicron worries
-0.2171898391274464
2021-12-09 00:00:00


In [14]:
d=namedtuple('d',['headline','numeric'])
data=namedtuple('Data',['data','target'])

test_set_2019=[]
test_set_2020=[]
test_set_2021=[]


for i in range(2348,2606):
    date=sx_ret['Date'][i]
    headline=reuters[reuters['Date']==date]
    if(headline.empty):
        continue
    headline=headline.iloc[0]
    headline=utils.tensorFromSentence(lang,headline['Headline'])
    numeric=sx5e_norm[i-27-5 : i-27]
    ret=sx_ret['Ret'][i]
    ret=torch.tensor(ret)
    r=(ret-mean_ret)/std_ret
    d1=d(headline,numeric)
    da=data(d1,r)
    test_set_2019.append(da)

for i in range(2606,2863):
    date=sx_ret['Date'][i]
    headline=reuters[reuters['Date']==date]
    if(headline.empty):
        continue
    headline=headline.iloc[0]
    headline=utils.tensorFromSentence(lang,headline['Headline'])
    numeric=sx5e_norm[i-27-5 : i-27]
    ret=sx_ret['Ret'][i]
    ret=torch.tensor(ret)
    r=(ret-mean_ret)/std_ret
    d1=d(headline,numeric)
    da=data(d1,r)
    test_set_2020.append(da)
    
for i in range(2863,3103):
    date=sx_ret['Date'][i]
    headline=reuters[reuters['Date']==date]
    if(headline.empty):
        continue
    headline=headline.iloc[0]
    headline=utils.tensorFromSentence(lang,headline['Headline'])
    numeric=sx5e_norm[i-27-5 : i-27]
    ret=sx_ret['Ret'][i]
    ret=torch.tensor(ret)
    r=(ret-mean_ret)/std_ret
    d1=d(headline,numeric)
    da=data(d1,r)
    test_set_2021.append(da)
    

In [15]:
test_loader_2019=torch.utils.data.DataLoader(test_set_2019, batch_size=1)
test_loader_2020=torch.utils.data.DataLoader(test_set_2020, batch_size=1)
test_loader_2021=torch.utils.data.DataLoader(test_set_2021, batch_size=1)


In [16]:
from utils import TextAndNumeric
from utils import TextOnlyGRU
from utils import LSTMNumeric

In [17]:
from utils import hit_profit
from utils import correct

In [53]:
tan=torch.load('models/text_and_numeric')
tog=torch.load('models/text_only_gru')
lstmn=torch.load('models/lstm_numeric')

In [20]:
loss_fn=torch.nn.MSELoss()

tan.eval()
with torch.no_grad():
        val_loss_buffer=[]
        val_ac=0
        cor=0
        hit_profit=0
        for i, (x,y) in enumerate(test_loader_2019):
            headline,numeric = x
            numeric=numeric.float()
            headline=headline.cuda()
            numeric=numeric.cuda()
            y=y.cuda()
            
            output=model(headline,numeric)
            output.float()
            y.float()
            val_loss_buffer.append(loss_fn(output,y).item())
            if(correct(output, y, std_ret, mean_ret)==1):
                hit_profit += correct(output, y, std_ret, mean_ret) * abs(y*std_ret - mean_ret)
            else:
                hit_profit-= abs(y*std_ret - mean_ret)
            
            cor+=correct(output,y,std_ret,mean_ret)
            
        val_acc=cor/len(test_loader_2019)
        val_loss=torch.mean(torch.tensor(val_loss_buffer))
        print(f"Test loss: {val_loss:.3f} Test Acc {val_acc:.5f}")
        print(hit_profit)

NameError: name 'model' is not defined

In [19]:
from utils import test_tan,test_text,test_numeric

In [47]:
def test_tan(model,loader):
    loss_fn=torch.nn.MSELoss()

    tan.eval()
    with torch.no_grad():
        val_loss_buffer=[]
        val_ac=0
        cor=0
        hit_profit=0
        for i, (x,y) in enumerate(loader):
            headline,numeric = x
            numeric=numeric.float()
            headline=headline.cuda()
            numeric=numeric.cuda()
            y=y.cuda()
            
            output=model(headline,numeric)
            output.float()
            y.float()
            val_loss_buffer.append(loss_fn(output,y).item())
            if(correct(output, y, std_ret, mean_ret)==1):
                hit_profit += correct(output, y, std_ret, mean_ret) * abs(y*std_ret - mean_ret)
            else:
                hit_profit-= abs(y*std_ret - mean_ret)
            
            cor+=correct(output,y,std_ret,mean_ret)
            
        val_acc=cor/len(loader)
        val_loss=torch.mean(torch.tensor(val_loss_buffer))
        print(f"Test loss: {val_loss:.3f} Test Acc {val_acc:.5f}")
        print(f"Test Hit Profit: {hit_profit.item():0.3f}")
        
        return val_loss,val_acc,hit_profit

In [48]:
def test_text(model,loader):
    loss_fn=torch.nn.MSELoss()

    model.eval()
    with torch.no_grad():
        val_loss_buffer=[]
        val_ac=0
        cor=0
        hit_profit=0
        for i, (x,y) in enumerate(loader):
            headline,numeric = x
            headline=headline.cuda()
            y=y.cuda()
            
            output=model(headline)
            output.float()
            y.float()
            val_loss_buffer.append(loss_fn(output,y).item())
            if(correct(output, y, std_ret, mean_ret)==1):
                hit_profit += correct(output, y, std_ret, mean_ret) * abs(y*std_ret - mean_ret)
            else:
                hit_profit-= abs(y*std_ret - mean_ret)
            
            cor+=correct(output,y,std_ret,mean_ret)
            
        val_acc=cor/len(loader)
        val_loss=torch.mean(torch.tensor(val_loss_buffer))
        print(f"Test loss: {val_loss:.3f} Test Acc {val_acc:.5f}")
        print(f"Test Hit Profit: {hit_profit.item():0.3f}")
        
        return val_loss,val_acc,hit_profit

In [51]:
def test_numeric(model,loader):
    loss_fn=torch.nn.MSELoss()

    model.eval()
    with torch.no_grad():
        val_loss_buffer=[]
        val_ac=0
        cor=0
        hit_profit=0
        for i, (x,y) in enumerate(loader):
            headline,numeric = x
            numeric=numeric.float()
            numeric=numeric.cuda()
            y=y.cuda()
            
            output=model(numeric)
            output.float()
            y.float()
            val_loss_buffer.append(loss_fn(output,y).item())
            if(correct(output, y, std_ret, mean_ret)==1):
                hit_profit += correct(output, y, std_ret, mean_ret) * abs(y*std_ret - mean_ret)
            else:
                hit_profit-= abs(y*std_ret - mean_ret)
            
            cor+=correct(output,y,std_ret,mean_ret)
            
        val_acc=cor/len(loader)
        val_loss=torch.mean(torch.tensor(val_loss_buffer))
        print(f"Test loss: {val_loss:.3f} Test Acc {val_acc:.5f}")
        print(f"Test Hit Profit: {hit_profit.item():0.3f}")
        
        return val_loss,val_acc,hit_profit

In [54]:
test_tan(tan,test_loader_2019)
test_tan(tan,test_loader_2020)
test_tan(tan,test_loader_2021)

Test loss: 0.489 Test Acc 0.49372
Test Hit Profit: -0.861
Test loss: 2.502 Test Acc 0.56031
Test Hit Profit: 22.796
Test loss: 0.568 Test Acc 0.52500
Test Hit Profit: 32.509


(tensor(0.5680),
 0.525,
 tensor([32.5089], device='cuda:0', dtype=torch.float64))

In [49]:
test_text(tog,test_loader_2019)
test_text(tog,test_loader_2020)
test_text(tog,test_loader_2021)

Test loss: 0.438 Test Acc 0.45607
Test Hit Profit: -4.375
Test loss: 2.437 Test Acc 0.49416
Test Hit Profit: 24.061
Test loss: 0.586 Test Acc 0.47917
Test Hit Profit: 5.428


(tensor(0.5856),
 0.4791666666666667,
 tensor([5.4277], device='cuda:0', dtype=torch.float64))

In [52]:
test_numeric(lstmn,test_loader_2019)
test_numeric(lstmn,test_loader_2020)
test_numeric(lstmn,test_loader_2021)

Test loss: 0.401 Test Acc 0.56485
Test Hit Profit: 5.689
Test loss: 2.442 Test Acc 0.52529
Test Hit Profit: -12.244
Test loss: 0.539 Test Acc 0.57917
Test Hit Profit: 7.666


(tensor(0.5387),
 0.5791666666666667,
 tensor([7.6655], device='cuda:0', dtype=torch.float64))